#ifndef ASSET_IDS_H
#define ASSET_IDS_H

typedef enum {
    TEXTURE_PLAYER,
    TEXTURE_CRAB_1,
    TEXTURE_CRAB_2,
    TEXTURE_OCTO_1,
    TEXTURE_OCTO_2,
    TEXTURE_SQUID_1,
    TEXTURE_SQUID_2,
    TEXTURE_OVNI,

    TEXTURE_BARRIER_0,
    TEXTURE_BARRIER_1,
    TEXTURE_BARRIER_2,
    TEXTURE_BARRIER_3,
    TEXTURE_BARRIER_4,
    TEXTURE_BARRIER_5,
    TEXTURE_BARRIER_6,
    TEXTURE_BARRIER_7,
    TEXTURE_BARRIER_8,
    TEXTURE_BARRIER_9,

    TEXTURE_COUNT
} TextureID;

#endif
